"use client";
import { useEffect, useState, type ReactNode } from "react";
import { money, packages, type Extra, type PackageName } from "@/lib/data";
type Details={childName:string;age:string;parentName:string;phone:string}; type Slot={event_date:string;time_slot:string};
type Props={open:boolean;onClose:()=>void;packageName:PackageName;setPackage:(x:PackageName)=>void;kids:number;setKids:(x:number)=>void;extras:Extra[]};
export function BookingModal(p:Props){
 const[step,setStep]=useState(1),[slot,setSlot]=useState<Slot|null>(null),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const[details,setDetails]=useState<Details>({childName:"",age:"",parentName:"",phone:""}); const total=packages.find(x=>x.name===p.packageName)!.price+p.extras.reduce((a,x)=>a+x.price,0);
 useEffect(()=>{if(!p.open)return;setError("");fetch("/api/availability").then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setSlots(body.slots)}).catch(e=>setError(e.message))},[p.open]);
 const close=()=>{p.onClose();setStep(1);setSlot(null);setError("")};
 const next=()=>{setError("");if(step===1&&(!details.childName||!details.age)){setError("Completá el nombre y la edad.");return}if(step===2&&(!slot||!details.parentName||!details.phone)){setError("Elegí un horario y completá tus datos.");return}setStep(x=>x+1)};
 const confirm=async()=>{if(!slot)return;setLoading(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...details,eventDate:slot.event_date,timeSlot:slot.time_slot.slice(0,5),packageName:p.packageName,kids:p.kids,extras:p.extras.map(x=>x.name)})});const body=await response.json();if(!response.ok)throw new Error(body.error);setStep(4)}catch(e){setError(e instanceof Error?e.message:"No pudimos enviar la consulta.")}finally{setLoading(false)}};
 if(!p.open)return null; return <div className="modal-wrap"><div className="modal-backdrop" onClick={close}/><section className="modal" role="dialog" aria-modal="true" aria-labelledby="bookingTitle"><button className="modal-close" onClick={close} aria-label="Cerrar">×</button><div className="steps">{[1,2,3].map(x=><span key={x} className={x<=step?"active":""}>{x}</span>)}</div>
 {step===1&&<><h2 id="bookingTitle">Tu fiesta empieza acá</h2><p className="sub">Contanos lo básico para verificar disponibilidad.</p><div className="form-grid"><Field label="Nombre de quien cumple"><input value={details.childName} onChange={e=>setDetails({...details,childName:e.target.value})} placeholder="Ej. Olivia"/></Field><Field label="Edad que cumple"><input value={details.age} onChange={e=>setDetails({...details,age:e.target.value})} type="number" min="1" max="14"/></Field><Field label="Paquete"><select value={p.packageName} onChange={e=>p.setPackage(e.target.value as PackageName)}>{packages.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Cantidad de niños"><input value={p.kids} onChange={e=>p.setKids(Number(e.target.value))} type="number" min="5" max="40"/></Field></div><Next onClick={next}>Elegir fecha</Next></>}
 {step===2&&<><h2 id="bookingTitle">¿Qué día les sirve?</h2><p className="sub">Horarios disponibles en tiempo real.</p><div className="calendar">{slots.map(s=>{const d=new Date(`${s.event_date}T12:00:00`),key=s.event_date+s.time_slot;return <button key={key} className={`date ${slot?.event_date===s.event_date&&slot?.time_slot===s.time_slot?"active":""}`} onClick={()=>setSlot(s)}><span>{d.toLocaleDateString("es-UY",{weekday:"short"})}</span><strong>{d.getDate()}</strong><span>{s.time_slot.slice(0,5)}</span></button>})}</div>{!slots.length&&!error&&<p className="sub">Buscando fechas…</p>}<div className="form-grid"><Field label="Tu nombre"><input value={details.parentName} onChange={e=>setDetails({...details,parentName:e.target.value})} placeholder="Nombre y apellido"/></Field><Field label="WhatsApp"><input value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})} placeholder="099 123 456"/></Field></div><Next onClick={next}>Revisar consulta</Next></>}
 {step===3&&slot&&<><h2 id="bookingTitle">Repasemos</h2><p className="sub">Todavía no se te cobrará nada.</p><div className="summary"><div><span>Festejo</span><strong>{details.childName} · {details.age} años</strong></div><div><span>Fecha</span><strong>{new Date(`${slot.event_date}T12:00:00`).toLocaleDateString("es-UY",{dateStyle:"long"})} · {slot.time_slot.slice(0,5)}</strong></div><div><span>Paquete</span><strong>{p.packageName} · {p.kids} niños</strong></div><div><span>Estimado</span><strong>{money(total)}</strong></div></div><button className="primary full next" disabled={loading} onClick={confirm}>{loading?"Enviando…":"Enviar consulta ✓"}<span>→</span></button></>}
 {error&&<p className="form-error" role="alert">{error}</p>}{step===4&&<div className="success"><div className="success-icon">✓</div><h2>¡Consulta enviada!</h2><p className="sub">La solicitud quedó registrada. El equipo de Nube puede revisarla y confirmarte el horario.</p><button className="primary" onClick={close}>Volver al sitio</button></div>}</section></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="field"><label>{label}</label>{children}</div>} function Next({onClick,children}:{onClick:()=>void;children:ReactNode}){return <button className="primary full next" onClick={onClick}>{children}<span>→</span></button>}
