"use client";
import { useEffect, useState, type ReactNode } from "react";
import { money, packageDisplayName, packages, type Extra, type PackageName } from "@/lib/data";
type Details={childName:string;age:string;parentName:string;phone:string}; type Slot={event_date:string;time_slot:string};
type Props={open:boolean;onClose:()=>void;packageName:PackageName;setPackage:(x:PackageName)=>void;kids:number;setKids:(x:number)=>void;extras:Extra[]};
export function BookingModal(p:Props){
 const[step,setStep]=useState(1),[slot,setSlot]=useState<Slot|null>(null),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const[details,setDetails]=useState<Details>({childName:"",age:"",parentName:"",phone:""}); const total=packages.find(x=>x.name===p.packageName)!.price+p.extras.reduce((a,x)=>a+x.price,0);
 useEffect(()=>{if(!p.open)return;setError("");fetch("/api/availability").then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setSlots(body.slots)}).catch(e=>setError(e.message))},[p.open]);
 const close=()=>{p.onClose();setStep(1);setSlot(null);setError("")};
 const next=()=>{setError("");if(step===1&&(!details.childName||!details.age)){setError("Enter the child's name and age.");return}if(step===2&&(!slot||!details.parentName||!details.phone)){setError("Choose a time and complete your details.");return}setStep(x=>x+1)};
 const confirm=async()=>{if(!slot)return;setLoading(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...details,eventDate:slot.event_date,timeSlot:slot.time_slot.slice(0,5),packageName:p.packageName,kids:p.kids,extras:p.extras.map(x=>x.name)})});const body=await response.json();if(!response.ok)throw new Error(body.error);setStep(4)}catch(e){setError(e instanceof Error?e.message:"We could not send the request.")}finally{setLoading(false)}};
 if(!p.open)return null; return <div className="modal-wrap"><div className="modal-backdrop" onClick={close}/><section className="modal" role="dialog" aria-modal="true" aria-labelledby="bookingTitle"><button className="modal-close" onClick={close} aria-label="Close">×</button><div className="steps">{[1,2,3].map(x=><span key={x} className={x<=step?"active":""}>{x}</span>)}</div>
 {step===1&&<><h2 id="bookingTitle">Your garden visit starts here</h2><p className="sub">Share the basics so we can check availability.</p><div className="form-grid"><Field label="Young grower's name"><input value={details.childName} onChange={e=>setDetails({...details,childName:e.target.value})} placeholder="e.g. Olivia"/></Field><Field label="Age"><input value={details.age} onChange={e=>setDetails({...details,age:e.target.value})} type="number" min="1" max="14"/></Field><Field label="Program"><select value={p.packageName} onChange={e=>p.setPackage(e.target.value as PackageName)}>{packages.map(x=><option key={x.name} value={x.name}>{packageDisplayName(x.name)}</option>)}</select></Field><Field label="Number of children"><input value={p.kids} onChange={e=>p.setKids(Number(e.target.value))} type="number" min="5" max="40"/></Field></div><Next onClick={next}>Choose a date</Next></>}
 {step===2&&<><h2 id="bookingTitle">Which day works for you?</h2><p className="sub">Available times are updated live.</p><div className="calendar">{slots.map(s=>{const d=new Date(`${s.event_date}T12:00:00`),key=s.event_date+s.time_slot;return <button key={key} className={`date ${slot?.event_date===s.event_date&&slot?.time_slot===s.time_slot?"active":""}`} onClick={()=>setSlot(s)}><span>{d.toLocaleDateString("en-US",{weekday:"short"})}</span><strong>{d.getDate()}</strong><span>{s.time_slot.slice(0,5)}</span></button>})}</div>{!slots.length&&!error&&<p className="sub">Looking for dates…</p>}<div className="form-grid"><Field label="Your name"><input value={details.parentName} onChange={e=>setDetails({...details,parentName:e.target.value})} placeholder="Full name"/></Field><Field label="WhatsApp"><input value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})} placeholder="099 123 456"/></Field></div><Next onClick={next}>Review request</Next></>}
 {step===3&&slot&&<><h2 id="bookingTitle">Review your visit</h2><p className="sub">You will not be charged yet.</p><div className="summary"><div><span>Young grower</span><strong>{details.childName} · {details.age} years old</strong></div><div><span>Date</span><strong>{new Date(`${slot.event_date}T12:00:00`).toLocaleDateString("en-US",{dateStyle:"long"})} · {slot.time_slot.slice(0,5)}</strong></div><div><span>Program</span><strong>{packageDisplayName(p.packageName)} · {p.kids} young growers</strong></div><div><span>Estimate</span><strong>{money(total)}</strong></div></div><button className="primary full next" disabled={loading} onClick={confirm}>{loading?"Sending…":"Send request ✓"}<span>→</span></button></>}
 {error&&<p className="form-error" role="alert">{error}</p>}{step===4&&<div className="success"><div className="success-icon">✓</div><h2>Request sent!</h2><p className="sub">Your request is recorded. The Nube garden team will review it and confirm the time.</p><button className="primary" onClick={close}>Back to the site</button></div>}</section></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="field"><label>{label}</label>{children}</div>} function Next({onClick,children}:{onClick:()=>void;children:ReactNode}){return <button className="primary full next" onClick={onClick}>{children}<span>→</span></button>}
